dubbo:
  application:
    name: dubbo-springboot-demo-provider
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  protocols:
    dubbo:
      name: dubbo
      port: 20880
    tri:
      name: tri
      port: 20990


server:
  port: 8081

logging:
  level:
    root: debug